# Railway configuration for ScraperLLM
[build]
builder = "dockerfile"
dockerfile = "Dockerfile.railway.optimized"  # Using our size-optimized Dockerfile

[deploy]
start_command = "uvicorn api.main:app --host 0.0.0.0 --port $PORT --workers 2"

[build.railway]
builder = "dockerfile"
build_timeout = 900  # 15 minutes (reduced from 30)

# Environment variables
[build.railway.variables]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONPATH = "/app"

# Health check configuration
[build.railway.healthcheck]
path = "/api/health"
initial_delay = 30
timeout = 10
interval = 60
threshold = 3

# Resource allocation - reduced for faster startup
[build.railway.resources]
cpu = 1
memory = 1024

# Simple scaling for initial deployment
[build.railway.scaling]
min_instances = 1
max_instances = 1  # Start with just one instance
target_cpu = 70
target_memory = 80

# Cache settings
[build.railway.cache]
paths = ["~/.cache/pip"]  # Simplified cache paths
